# Generated by Django 4.2 on 2023-05-19 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MaxValueValidator(1000000000000), django.core.validators.MinValueValidator(0)], verbose_name='total hors taxe')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MaxValueValidator(1000000000000), django.core.validators.MinValueValidator(0)], verbose_name='total ttc')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='articles')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
    ]
