# Generated by Django 4.2 on 2023-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='titre')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='activé ?')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='articles')),
            ],
        ),
    ]
