"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import Csv, config
import moneyed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECRET_KEY = config("SECRET_KEY", default="django-insecure$simple.settings.local")
DEBUG = config("DEBUG", default=True, cast=bool)
# ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())
ALLOWED_HOSTS = ['*']

SECRET_KEY = "django-insecure-%5lhesscc1+=n&wn^!$)vk0b29*n$c@uo-*s8d(0p%l9!i1c!*"

# # # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []


INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
    
    'tinymce',
    'djmoney',
    'import_export',
    "mptt",
    #'versatileimagefield',
    "phonenumber_field",
    
    
    
    "core.apps.account",
    "core.apps.products",
    "core.apps.contact",
    "core.apps.search",
    "core.apps.cart",
    "core.apps.social",
    "core.apps.shop",
    "core.apps.tags",
    "core.apps.instagram",
    "core.apps.about",
    "core.apps.blog",
    "core.apps.marketing",
    "core.apps.order",
    "core.apps.billing",
    "core.apps.addresses",
    "core.apps.analytics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.apps.social.context_processors.link",
                "core.apps.products.context_processors.categories",
                "core.apps.instagram.context_processors.instagramm",
                "core.apps.blog.context_processors.blog_latest",
                "core.apps.cart.context_processors.basket",
                # "core.apps.shop.context_processors.cart_quantity"
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"







# DATABASES = {
#     "default": dj_database_url.config(
#         default=config("DATABASE_URL", default="postgres://simple:simple@localhost:5432/simple"),
#         conn_max_age=600,
#     )
# }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/




LANGUAGE_CODE = config("LANGUAGE_CODE", default="fr-FR")

TIME_ZONE = config("TIME_ZONE", default="Africa/Conakry")

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "locale"]











# LANGUAGE_CODE = "fr-FR"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True










# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "static/"

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.parent.parent / "static"

STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)




MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR.parent.parent / "media"






# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "fr_FR",  # To force a specific language instead of the Django current language.
}





GNF = moneyed.add_currency(
    code='BOB',
    numeric='068',
    name='Guinean franc',
    countries=('GUINEA', )
)


CURRENCIES = ('USD', 'EUR')
CURRENCY_CHOICES = [('USD', 'USD $'), ('EUR', 'EUR €'), ('GNF', 'GNF')]

USE_THOUSAND_SEPARATOR = True 

# AUTH_USER_MODEL = 'accounts.User'

LOGOUT_REDIRECT_URL = "/login/"
LOGOUT_REDIRECT_URL = "/"  # new

SIMPLE_ENVIRONMENT = config("SIMPLE_ENVIRONMENT", default="local")


# MAILCHIMP CREDENTIALS
MAILCHIMP_API_KEY = "e3a7bc63e4b0cfda697e18ec938a44be-us20"
MAILCHIMP_DATA_CENTER = "us20"
MAILCHIMP_EMAIL_LIST_ID = "a9e03c576c"



AUTH_USER_MODEL = 'account.User'
LOGIN_URL = 'accounts:login'
LOGIN_URL_REDIRECT = '/'
LOGOUT = 'accounts:logout'

# AUTH_USER_MODEL = "accounts.CustomUser"  # ne


FORCE_SESSION_TO_ONE = False
FORCE_INACTIVE_USER_END_SESSION = False


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'abdulkabirkeita825@gmail.com' #sendgrid
EMAIL_HOST_PASSWORD = '****************'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'abdulkabirkeita825@gmail.com'

MANAGERS = (
    ('abdul', 'abdul@gmail.com')
)

ADMINS = MANAGERS