# Generated by Django 4.2 on 2023-05-19 16:45

import core.apps.instagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to=core.apps.instagram.models.upload_insta_image_path)),
            ],
        ),
    ]
