# Generated by Django 4.2 on 2023-05-19 16:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('livraison', 'Livraison'), ('facturation', 'Facturation')], max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='nom')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True, verbose_name='prenom')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='telephone')),
                ('country', models.CharField(default='Guinée', max_length=200, verbose_name='pays')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('address', models.CharField(max_length=150, verbose_name='adresse')),
                ('street_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rue')),
                ('message', models.TextField(blank=True, null=True)),
                ('billing_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ('-id',),
            },
        ),
    ]
