# Generated by Django 4.2 on 2023-05-14 20:33

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('livraison', 'Livraison'), ('facturation', 'Facturation')], max_length=50, verbose_name="type d'adresse")),
                ('lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='nom')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True, verbose_name='prenom')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='telephone')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='pays')),
                ('state', models.CharField(default='Conakry', max_length=50, verbose_name='region')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('street_address', models.CharField(max_length=150, verbose_name='quartier/rue')),
                ('message', models.TextField()),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ('-id',),
            },
        ),
    ]
